# Generated by Django 4.0.5 on 2022-06-17 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_use_referer',
            field=models.ManyToManyField(blank=True, related_name='user_referer', to=settings.AUTH_USER_MODEL),
        ),
    ]
