# Generated by Django 4.0.5 on 2022-06-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_photo_alter_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablighat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('information', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(upload_to='tablighat')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
