# Generated by Django 4.0.5 on 2022-06-27 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ')),
                ('code_color', models.CharField(max_length=40, verbose_name='کد رنگ را وارد کنید.')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rate', models.IntegerField(default=1)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('is_replay', models.BooleanField(default=False)),
                ('total_like', models.IntegerField(default=0)),
                ('is_like', models.ManyToManyField(blank=True, related_name='likeComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField(default=0, verbose_name='تعداد موجودی محصول')),
                ('unit_price', models.BigIntegerField(verbose_name='قیمت محصول')),
                ('discount', models.IntegerField(verbose_name='تخفیف')),
                ('information', models.TextField(verbose_name='اطلاعات بیشتر محصول')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('image', models.ImageField(upload_to='products', verbose_name='عکس محصول')),
                ('sale', models.BooleanField(default=False, verbose_name='فروخته شده است؟')),
                ('is_varient', models.CharField(choices=[(None, 'None'), ('size', 'سایز'), ('color', 'رنگ')], default=None, max_length=10)),
                ('total_view', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='home.brand')),
                ('category', models.ManyToManyField(related_name='productCategoryRel', to='home.category', verbose_name='دسته\u200cبندی محصول')),
                ('is_favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('is_like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='سایز')),
            ],
        ),
        migrations.CreateModel(
            name='VarientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('unit_price', models.BigIntegerField(verbose_name='قیمت محصول')),
                ('discount', models.IntegerField(verbose_name='تخفیف')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('image', models.ImageField(upload_to='products', verbose_name='عکس محصول')),
                ('sale', models.BooleanField(default=False, verbose_name='فروخته شده است؟')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='home.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.size')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_like', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayComment', to='home.comment')),
                ('is_like', models.ManyToManyField(blank=True, related_name='likeReplay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
