# Generated by Django 4.0.5 on 2022-06-27 21:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_imagegallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablighat',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
