# Generated by Django 4.0.5 on 2022-06-27 21:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_tablighat_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablighat',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
