# Generated by Django 4.0.5 on 2022-06-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replya_rel', to='home.comment'),
        ),
        migrations.DeleteModel(
            name='ReplayComment',
        ),
    ]
