# Generated by Django 4.0.5 on 2022-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment_replay_delete_replaycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_varient',
            field=models.CharField(choices=[(None, 'None'), ('size', 'سایز'), ('color', 'رنگ')], max_length=10),
        ),
    ]
