# Generated by Django 4.0.5 on 2022-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_is_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_varient',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('size', 'سایز'), ('color', 'رنگ')], max_length=10, null=True),
        ),
    ]
